### ISSUE TITLE
rosconsole_bridge now fails wstool update

### ISSUE THREAD

**Issue by t1jump** [ros/rosconsole_bridge#2]
rkrs@bbone1:~/ros_catkin_ws/src$ wstool update rosconsole_bridge[rosconsole_bridge] Fetching https://github.com/ros/rosconsole_bridge.git (version rosconsole_bridge-release-release-groovy-rosconsole_bridge-0.2.6-0) to /home/rkrs/ros_catkin_ws/src/rosconsole_bridge
WARNING [vcstools] Command failed: 'git checkout rosconsole_bridge-release-release-groovy-rosconsole_bridge-0.2.6-0'
 run at: '/home/rkrs/ros_catkin_ws/src/rosconsole_bridge'
 errcode: 1:
error: pathspec 'rosconsole_bridge-release-release-groovy-rosconsole_bridge-0.2.6-0' did not match any file(s) known to git.
[/vcstools]
Exception caught during install: Error processing 'rosconsole_bridge' : [rosconsole_bridge] Checkout of https://github.com/ros/rosconsole_bridge.git version rosconsole_bridge-release-release-groovy-rosconsole_bridge-0.2.6-0 into /home/rkrs/ros_catkin_ws/src/rosconsole_bridge failed.

ERROR in config: Error processing 'rosconsole_bridge' : [rosconsole_bridge] Checkout of https://github.com/ros/rosconsole_bridge.git version rosconsole_bridge-release-release-groovy-rosconsole_bridge-0.2.6-0 into /home/rkrs/ros_catkin_ws/src/rosconsole_bridge failed.

**Comment by dirk-thomas** [comment]
Could you please post the entry for rosconsole_bridge from your .rosinstall file? You did you retrieve that?

**Comment by t1jump** [comment]
I removed rosconsole_bridge from the src file and started the install without it (./src/catkin/bin/catkin_make_isolated --install). It will take several hours for this to complete before I can run install with rosconsole_bridge again to throw the error that came up during install.

**Comment by tfoote** [comment]
Your pathspec looks like a tag in the release repo (https://github.com/ros-gbp/rosconsole_bridge-release) , but the url points to the upstream repo in that incarnation this will never work  

How did you generate your rosinstall file? DId you modify anything?

**Comment by t1jump** [comment]
Below is the process I used. This worked fine on a build Saturday and failed on a new build today.

Fetch the Core Packages for the Desired ROS Variant into the Catkin Workspace: (3 mins)
$ mkdir ~/ros_catkin_ws
$ cd ~/ros_catkin_ws
$ wstool init src -j8 http://packages.ros.org/web/rosinstall/generate/raw/groovy/robot

Update
$ cd ~/ros_catkin_ws/src
$ wstool update

Install ROS Catkin Dependencies:
$ cd ~/ros_catkin_ws
$ rosdep install --from-paths src --ignore-src --rosdistro groovy -y

Build ROS Catkin Packages:
$ cd ~/ros_catkin_ws (just a note to remind to be in this directory)
$ ./src/catkin/bin/catkin_make_isolated --install

**Comment by t1jump** [comment]
After the error when trying to install using $ ./src/catkin/bin/catkin_make_isolated --install I moved into the src directory and tried wstool set

$ cd ~/ros_catkin_ws/src
$ wstool set rosconsole_bridge https://github.com/ros/rosconsole_bridge.git --git -y
$ wstool update rosconsole_bridge

and with this I get the error in the initial post above.

**Comment by dirk-thomas** [comment]
When fetching the above mentioned URL of the rosinstall generator the entry for rosconsole_bridge looks like:

```
- tar: {local-name: rosconsole_bridge, uri: 'https://github.com/ros-gbp/rosconsole_bridge-release/archive/release/groovy/rosconsole_bridge/0.2.7-0.tar.gz', version: rosconsole_bridge-release-release-groovy-rosconsole_bridge-0.2.7-0}
```

Before the latest release you will have received a similar entry for version 0.2.6. Your error message indicated that the URL of the repository is different - pointing to the non-gbp repository. Have you manually altered the rosinstall file? If yes, that entry is now just wrong.

You should fetch a current rosinstall file from the url and use that one to update your workspace. Note: `wstool update` will not fetch new versions of a package.

Since this is clearly not a rosconsole_bridge issue I will mark the issue as closed. Please feel free to continue commenting on the ticket.

**Comment by t1jump** [comment]
I made no changes to the rosinstall file. I'm not sure where the rosinstall file comes in but the steps I followed previous to fetching the core packages are shown below. Did the rosinstall file get changed at the source (how would this get checked)?

Install Pre-reqs for and Download ROS Catkin Packages

Sources List:
$ sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu quantal main" > /etc/apt/sources.list.d/ros-latest.list'

Keys:
$ wget http://packages.ros.org/ros.key -O - | sudo apt-key add -

Update:
$ sudo apt-get update

Bootstrap dependencies (Ubuntu):
$ sudo apt-get install python-rosdep python-wstool build-essential

Initialize rosdep: (1 min)
$ sudo rosdep init
$ rosdep update

**Comment by tfoote** [comment]
When you call wstool set to set the url but not the branch you are checking out. (That changes the rosinstall file)  You need to use the --version-new option when calling wstool set.

**Comment by t1jump** [comment]
Should I be concerned that other packages I called without using the --version-new option could have issues?

**Comment by tfoote** [comment]
Yes
